name: CI

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: test
        uses: actions/setup-node@v2
        
      - run: npm ci
      - run: npm test
